services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    command: start --log debug --user ${SURREAL_USER} --pass ${SURREAL_PASSWORD}
    environment:
      SURREAL_URL: ${SURREAL_URL}
      SURREAL_USER: ${SURREAL_USER}
      SURREAL_PASSWORD: ${SURREAL_PASSWORD}
      SURREAL_NAMESPACE: ${SURREAL_NAMESPACE}
      SURREAL_DB: ${SURREAL_DB}
    ports:
      - 8000:8000
    volumes:
      - surrealdb_data:/db
    networks:
      - woka-net
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
    volumes:
      - minio_data:/data
    networks:
      - woka-net
  woka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: woka-server
    depends_on:
      surrealdb:
        condition: service_started
      minio:
        condition: service_started
    environment:
      SURREAL_URL: ${SURREAL_URL}
      SURREAL_USER: ${SURREAL_USER}
      SURREAL_PASSWORD: ${SURREAL_PASSWORD}
      SURREAL_NAMESPACE: ${SURREAL_NAMESPACE}
      SURREAL_DB: ${SURREAL_DB}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      ENV: ${ENV}
    ports:
      - 8080:8080
    volumes:
      - ./config:/app/config:ro
    networks:
      - woka-net

volumes:
  surrealdb_data:
  minio_data:

networks:
  woka-net:
    driver: bridge
